apiVersion: v1
kind: ServiceAccount
metadata:
  name: nemo-retriever-sa
  namespace: syntharbiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemo-retriever
  namespace: syntharbiter
  labels:
    app: nemo-retriever
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nemo-retriever
  template:
    metadata:
      labels:
        app: nemo-retriever
    spec:
      serviceAccountName: nemo-retriever-sa
      nodeSelector:
        workload: gpu-inference
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
      - name: retriever
        image: nvcr.io/nvidia/nemo-retriever:latest
        env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nvidia-ngc-credentials
              key: api-key
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nemo-retriever
  namespace: syntharbiter
spec:
  type: ClusterIP
  selector:
    app: nemo-retriever
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

