AWSTemplateFormatVersion: '2010-09-09'
Description: 'SynthArbiter - Application Load Balancer & Monitoring'

Resources:
  # CloudWatch Log Groups
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/eks/syntharbiter/app
      RetentionInDays: 30

  NemoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/eks/syntharbiter/nemo
      RetentionInDays: 30

  # CloudWatch Alarms
  ErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: syntharbiter-5xx-errors
      AlarmDescription: Alert when 5XX error rate exceeds 5%
      MetricName: 5XXError
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold

  LatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: syntharbiter-high-latency
      AlarmDescription: Alert when average latency exceeds 30 seconds
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 30
      ComparisonOperator: GreaterThanThreshold

Outputs:
  AppLogGroupName:
    Description: Application log group name
    Value: !Ref AppLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-AppLogGroup'

  NemoLogGroupName:
    Description: NeMo log group name
    Value: !Ref NemoLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-NemoLogGroup'

