name: Setup AWS Parameters

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['config/parameters.json']

jobs:
  sync-parameters:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-SynthArbiter
          aws-region: ${{ github.event.inputs.region || 'us-east-1' }}
      
      - name: Sync Parameters to SSM
        run: |
          jq -r '.dev // empty | to_entries[] | "\(.key)=\(.value)"' config/parameters.json | while IFS='=' read -r key value; do
            aws ssm put-parameter \
              --name "/syntharbiter/$key" \
              --value "$value" \
              --type String \
              --overwrite
            echo "✓ Updated parameter: /syntharbiter/$key"
          done
      
      - name: Setup Secrets (if not exists)
        run: |
          if ! aws secretsmanager describe-secret --secret-id /syntharbiter/nvidia-ngc-api-key 2>/dev/null; then
            aws secretsmanager create-secret \
              --name /syntharbiter/nvidia-ngc-api-key \
              --secret-string "${{ secrets.NVIDIA_NGC_API_KEY }}"
            echo "✓ Created NGC API key secret"
          else
            aws secretsmanager update-secret \
              --secret-id /syntharbiter/nvidia-ngc-api-key \
              --secret-string "${{ secrets.NVIDIA_NGC_API_KEY }}"
            echo "✓ Updated NGC API key secret"
          fi

